# Generated by Django 3.0.5 on 2020-04-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_auto_20200405_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrer',
            name='link',
            field=models.CharField(default='boo', max_length=50),
            preserve_default=False,
        ),
    ]
